# Efficient Frontier

In [ ]:
import pandas as pd

ind = pd.read_csv(
    "../data/ind30_m_vw_rets.csv", index_col=0, parse_dates=True, header=0
)
ind.head()

/tmp/ipykernel_14881/2091532650.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ind = pd.read_csv("../data/ind30_m_vw_rets.csv", index_col=0, parse_dates=True, header=0)

,Food,Beer,Smoke,Games,Books,Hshld,Clths,Hlth,Chems,Txtls,...,Telcm,Servs,BusEq,Paper,Trans,Whlsl,Rtail,Meals,Fin,Other
192607,0.56,-5.19,1.29,2.93,10.97,-0.48,8.08,1.77,8.14,0.39,...,0.83,9.22,2.06,7.70,1.93,-23.79,0.07,1.87,0.37,5.20
192608,2.59,27.03,6.50,0.55,10.01,-3.58,-2.51,4.25,5.50,8.14,...,2.17,2.02,4.39,-2.38,4.88,5.39,-0.75,-0.13,4.46,6.76
192609,1.16,4.02,1.26,6.58,-0.99,0.73,-0.51,0.69,5.33,2.31,...,2.41,2.25,0.19,-5.54,0.05,-7.87,0.25,-0.56,-1.23,-3.86
192610,-3.06,-3.31,1.06,-4.76,9.47,-4.68,0.12,-0.57,-4.76,1.00,...,-0.11,-2.00,-1.09,-5.08,-2.64,-15.38,-2.20,-4.11,-5.16,-8.49
192611,6.35,7.29,4.55,1.66,-5.80,-0.54,1.87,5.42,5.20,3.11,...,1.63,3.77,3.64,3.84,1.60,4.67,6.52,4.33,2.24,4.00

In [ ]:
import polars as pl

indpl = pl.read_csv("../data/ind30_m_vw_rets.csv", try_parse_dates=True)

indpl.head()

shape: (5, 31)
┌────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│        ┆ Food    ┆ Beer    ┆ Smoke   ┆ … ┆ Rtail   ┆ Meals   ┆ Fin     ┆ Other   │
│ ---    ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ i64    ┆ str     ┆ str     ┆ str     ┆   ┆ str     ┆ str     ┆ str     ┆ str     │
╞════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ 192607 ┆    0.56 ┆   -5.19 ┆    1.29 ┆ … ┆    0.07 ┆    1.87 ┆    0.37 ┆    5.20 │
│ 192608 ┆    2.59 ┆   27.03 ┆    6.50 ┆ … ┆   -0.75 ┆   -0.13 ┆    4.46 ┆    6.76 │
│ 192609 ┆    1.16 ┆    4.02 ┆    1.26 ┆ … ┆    0.25 ┆   -0.56 ┆   -1.23 ┆   -3.86 │
│ 192610 ┆   -3.06 ┆   -3.31 ┆    1.06 ┆ … ┆   -2.20 ┆   -4.11 ┆   -5.16 ┆   -8.49 │
│ 192611 ┆    6.35 ┆    7.29 ┆    4.55 ┆ … ┆    6.52 ┆    4.33 ┆    2.24 ┆    4.00 │
└────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘